# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff462be88358ca1efb41cec3d7097dc43e10d5a49a83b91e6e0295762f26ca9e22292a03dce02fd074a15855383b87b8aac409a9288ec23ffaee7ffa86595c0

test:
  secret_key_base: 1e7f5f8262fdddce7797e412233fdbbb25c2bebbf49adb515b41b8e58039ec9ae84544b831a5a1c54bda48c4cc617c80e6b1c08d1d964c53ab7d7c9a20265714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: 
#a26e44b54448f41c6078727b920f86b11e8b523e966850c8b904a21c19b04b5d843a905b2578c06732a18afd77c25a7a9d2204be0431273038f2852370f29b47
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
